<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Server</RootNamespace>
    <OutDir>$(ScriptsAssemblyDir)</OutDir>
    <PublishDir>$(ScriptsAssemblyDir)</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(ModernUORoot)Projects/Server/Server.csproj" Private="false" />
    <ProjectReference Include="$(ModernUORoot)Projects/UOContent/UOContent.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModernUO.Serialization.Generator" Version="4.1.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Migrations/*.v*.json" />
  </ItemGroup>

</Project>
